# Ubuntu 18.04 base image used for localops test.
#
# We do not need to run the steps below every time we want to test,
# and they are very time consuming.

FROM ubuntu:18.04

RUN apt update

RUN DEBIAN_FRONTEND=noninteractive apt upgrade --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

RUN DEBIAN_FRONTEND=noninteractive apt install --assume-yes sudo ubuntu-standard python3-distutils git

RUN useradd --shell /bin/bash --create-home --home-dir /home/test test --skel /etc/skel

RUN passwd -d test

RUN addgroup test sudo

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["su test -c 'cd ~/localops && ./bootstrap.sh'"]
