# Ubuntu 18.04 base image used for localops test.
#
# We do not need to run the steps below every time we want to test,
# and they are very time consuming.

FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt upgrade --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" && \
    apt install --assume-yes sudo ubuntu-standard python3-distutils git && \
    useradd --shell /bin/bash --create-home --home-dir /home/test test --skel /etc/skel && \
    passwd -d test && \
    addgroup test sudo

COPY . /home/test/localops/

RUN chown -R test:test /home/test/localops && \
    su test -c 'cd /home/test/localops && ./bootstrap.sh' && \
    rm -rf /home/test/localops

ENTRYPOINT ["/bin/bash", "-c"]
