- hosts: all
  gather_facts: false
  tasks:

  - name: Create user bin
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      mode: '744'
      state: directory

  - name: Add ~/bin to PATH
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      line: PATH=$HOME/bin:$PATH
