- hosts: all
  gather_facts: false
  tasks:

  - name: Create user bin
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      mode: '744'
      state: directory

  - name: Create symbolic link to localops.sh in ~/bin
    file:
      src: "{{ lookup('env', 'HOME') }}/.localops/localops.sh"
      dest: "{{ lookup('env', 'HOME') }}/bin/localops"
      state: link
