- hosts: all
  gather_facts: false
  tasks:

  - name: Enable direnv
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      line: eval "$(direnv hook bash)"

  - name: Check whether file .envrc exists
    stat:
      path: .envrc
    register: envrc

  - name: Create .envrc
    file:
      path: .envrc
      state: touch
    when: not envrc.stat.exists

  - name: Add /opt/python-3.9.1/bin to local PATH using direnv
    lineinfile:
      path: .envrc
      line: export PATH=${HOME}/.local/bin:/opt/python-3.9.1/bin:$PATH

  - name: Enable direnv in this dir
    shell: eval "$(direnv hook bash)" && direnv allow
