- hosts: all
  tasks:

    - name: Update apt cache, if older than a day
      become: yes
      become_user: root
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install Java
      become: yes
      become_user: root
      apt:
        state: latest
        pkg: default-jdk
