- name: Install Helm
  import_playbook: helm.yaml

# See https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html
- hosts: all
  gather_facts: false
  tasks:

  - name: Install PyYAML
    pip:
      name: PyYAML
      state: latest

  # https://docs.ansible.com/ansible/latest/collections/community/kubernetes/helm_repository_module.html
  - name: Add JupyterHub Helm repository
    community.kubernetes.helm_repository:
      name: jupyterhub
      repo_url: https://jupyterhub.github.io/helm-chart/

  # https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html#prepare-configuration-file
  - name: Generate a random hex string representing 32 bytes to use as a security token
    shell: openssl rand -hex 32
    register: security_token

  - debug:
      msg: "Security token created, write it down somewhere safe: {{ security_token.stdout }}"

  # https://docs.ansible.com/ansible/latest/collections/community/kubernetes/helm_module.html
  - name: Install JupyterHub Chart
    community.kubernetes.helm:
      chart_ref: jupyterhub/jupyterhub
      release_name: jupyterhub
      create_namespace: true
      release_namespace: jupyterhub
      release_values:
        proxy:
          secretToken: "{{ security_token.stdout }}"
      wait: yes
