# https://packagecloud.io/slacktechnologies/slack/install#manual-deb
#
# The examples have references to Ubuntu repositories, but looks like
# there are only Debian ones. Jessie is the latest

- hosts: all
  tasks:

    - name: Add Slack packagecloud apt repository signing key
      become: yes
      become_user: root
      apt_key:
        url: https://packagecloud.io/slacktechnologies/slack/gpgkey
        state: present

    - name: Add Slack packagecloud repo
      become: yes
      become_user: root
      apt_repository:
        repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        state: present

    - name: Update apt cache, if older than a day
      become: yes
      become_user: root
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install slack-desktop
      become: yes
      become_user: root
      apt:
        state: latest
        pkg: slack-desktop
