- name: Install curl
  import_playbook: curl.yaml

- name: Create ~/bin and add it to PATH
  import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Get Spring Boot CLI latest version
    shell: curl -Ls -o /dev/null -w %{url_effective} https://github.com/spring-projects/spring-boot/releases/latest | sed -e 's|.*/v\(.*\)|\1|'
    args:
      warn: false
    register: version

  - name: Download Spring Boot CLI
    unarchive:
      src: "https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/{{ version.stdout }}/spring-boot-cli-{{ version.stdout }}-bin.tar.gz"
      dest: /tmp
      remote_src: yes

  - name: Copy Spring Boot CLI binary to ~/bin
    copy:
      src: /tmp/spring-{{ version.stdout }}/bin/spring
      dest: "{{ lookup('env', 'HOME') }}/bin/spring-{{ version.stdout }}"
      mode: '0744'

  - name: Create ~/lib
    file:
      path: "{{ lookup('env', 'HOME') }}/lib"
      mode: '744'
      state: directory

  - name: Copy Spring Boot CLI library to ~/lib
    copy:
      src: "/tmp/spring-{{ version.stdout }}/lib/spring-boot-cli-{{ version.stdout }}.jar"
      dest: "{{ lookup('env', 'HOME') }}/lib"
      mode: '0744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/spring-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/spring"
      state: link
