- hosts: all
  tasks:

    - name: Add VirtualBox apt repository signing key
      become: yes
      become_user: root
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox apt repo
      become: yes
      become_user: root
      apt_repository:
        repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
        state: present

    - name: Update apt cache, if older than a day
      become: yes
      become_user: root
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install VirtualBox
      become: yes
      become_user: root
      apt:
        state: latest
        pkg: virtualbox-6.1
