- hosts: all
  gather_facts: false
  tasks:

  - name: Install Chef Workstation, version 20.12.205
    become: yes
    become_user: root
    apt:
      deb: https://packages.chef.io/files/stable/chef-workstation/20.12.205/ubuntu/20.04/chef-workstation_20.12.205-1_amd64.deb
