- hosts: all
  tasks:

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install gimp
    become: yes
    become_user: root
    apt:
      pkg: gimp
      state: latest

  # TODO this is only needed for Ubuntu 20.04
  - name: Install libgnomevfs2-common
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/g/gnome-vfs/libgnomevfs2-common_2.24.4-6.1ubuntu2_amd64.deb

  - name: Install libgnomevfs2
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/g/gnome-vfs/libgnomevfs2-0_2.24.4-6.1ubuntu2_amd64.deb

  - name: Install gnome-raw-thumbnailer
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/g/gnome-raw-thumbnailer/gnome-raw-thumbnailer_2.0.1-0ubuntu9_amd64.deb

  - name: Install libexiv2
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/main/e/exiv2/libexiv2-14_0.25-3.1_amd64.deb

#http://archive.ubuntu.com/ubuntu/pool/universe/u/ufraw/ufraw_0.22-3_amd64.deb

  - name: Install libgtkimageview0
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/g/gtkimageview/libgtkimageview0_1.6.4+dfsg-2_amd64.deb

  - name: Install gimp-ufraw
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/u/ufraw/gimp-ufraw_0.22-3_amd64.deb

  - name: Install ufraw-batch
    become: yes
    become_user: root
    apt:
      deb: http://archive.ubuntu.com/ubuntu/pool/universe/u/ufraw/ufraw-batch_0.22-3_amd64.deb
