- hosts: all
  gather_facts: false
  tasks:

  - name: Add Google Chrome apt repository signing key
    become: yes
    become_user: root
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present

  - name: Add Google Chrome apt repo
    become: yes
    become_user: root
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Google Chrome
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: google-chrome-stable
