- hosts: all
  gather_facts: false
  tasks:

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install curl
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: curl

  - name: Install unzip
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: unzip

  - name: Check whether .bashrc exists
    stat:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
    register: bashrc

    # ...

  - name: Check whether .zshrc exists
    stat:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
    register: zshrc

    # ...
