- hosts: all
  tasks:

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install NFS Server
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: nfs-kernel-server

  # The configuration below creates a local share you can mount on k8s pods.
  #
  # See https://kubernetes.io/docs/concepts/storage/volumes/#nfs

  - name: Create group nfs-mount
    become: yes
    become_user: root
    group:
      name: nfs-mount
      state: present

  - name: Create user nfs-mount
    become: yes
    become_user: root
    user:
      name: nfs-mount
      system: yes
      shell: /usr/bin/false
      create_home: no
      group: nfs-mount
      append: no
      state: present

  - name: Add this user to group docker
    become: yes
    become_user: root
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: nfs-mount
      append: yes

  - name: Create directory /srv/nfs
    become: yes
    become_user: root
    file:
      path: /srv/nfs
      mode: '775'
      owner: nfs-mount
      group: nfs-mount
      state: directory

  - name: Create line to add to /etc/exports
    become: yes
    become_user: root
    shell: echo "/srv/nfs localhost(rw,fsid=0,anonuid=$(id -u nfs-mount),anongid=$(id -g nfs-mount),sync,subtree_check)"
    register: etc_exports_line

  - name: Add directory /srv/nfs to /etc/exports
    become: yes
    become_user: root
    lineinfile:
      path: /etc/exports
      line: "{{ etc_exports_line.stdout }}"

  - name: Restart NFS Server
    become: yes
    become_user: root
    service:
      name: nfs-server
      state: restarted
      daemon_reload: yes
