- hosts: all
  tasks:

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install PHP
    become: yes
    become_user: root
    apt:
      pkg: php-cli
      state: latest

  - name: Install SimpleXML
    become: yes
    become_user: root
    apt:
      pkg: php-xml
      state: latest

  - name: Install Multibyte String
    become: yes
    become_user: root
    apt:
      pkg: php-mbstring
      state: latest

  - name: Install Internationalization Functions
    become: yes
    become_user: root
    apt:
      pkg: php-intl
      state: latest
