- hosts: all
  gather_facts: false
  tasks:

  - name: Install AWS CLI
    pip:
      executable: pip
      name: awscli
      state: latest
      extra_args:  --no-cache-dir --upgrade --force-reinstall --user
