- import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Get codacy-analysis-cli latest version
    shell: "curl -Ls -o /dev/null -w %{url_effective} https://github.com/codacy/codacy-analysis-cli/releases/latest | sed -e 's|.*/||'"
    args:
      warn: false
    register: version

  - name: Download codacy-analysis-cli
    unarchive:
      src: https://github.com/codacy/codacy-analysis-cli/archive/{{ version.stdout }}.tar.gz
      dest: /tmp
      remote_src: yes
      mode: '744'

  - name: Install codacy-analysis-cli
    shell: "cd /tmp/codacy-analysis-cli-* && make install PREFIX=/tmp && cp /tmp/bin/codacy-analysis-cli {{ lookup('env', 'HOME') }}/bin/codacy-analysis-cli-{{ version.stdout }}"

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/codacy-analysis-cli-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/codacy-analysis-cli"
      state: link
