- import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Get Helm latest version
    shell: "curl -Ls -o /dev/null -w %{url_effective} https://github.com/helm/helm/releases/latest | sed -e 's|.*/||'"
    args:
      warn: false
    register: version

  - name: Download Helm
    unarchive:
      src: https://get.helm.sh/helm-{{ version.stdout }}-linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes

  - name: Copy Helm binary to ~/bin
    copy:
      src: /tmp/linux-amd64/helm
      dest: "{{ lookup('env', 'HOME') }}/bin/helm-{{ version.stdout }}"
      mode: '0744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/helm-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/helm"
      state: link

  # https://galaxy.ansible.com/community/kubernetes
  - name: Install community.kubernetes Ansible collection
    shell: ansible-galaxy collection install community.kubernetes
