- import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  # FIXME This code is replicated in jenkins.yaml. Refactor using a module
  - name: Get kubeval latest version
    shell: "curl -Ls -o /dev/null -w %{url_effective} https://github.com/instrumenta/kubeval/releases/latest | sed -e 's|.*/||'"
    args:
      warn: false
    register: kubeval_version

  - name: Download kubeval
    unarchive:
      src: https://github.com/instrumenta/kubeval/releases/download/{{ kubeval_version.stdout }}/kubeval-linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes

  - name: Copy kubeval binary to ~/bin
    copy:
      src: /tmp/kubeval
      dest: "{{ lookup('env', 'HOME') }}/bin/kubeval-{{ kubeval_version.stdout }}"
      mode: '0744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/kubeval-{{ kubeval_version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/kubeval"
      state: link
