# See https://microk8s.io/docs/troubleshooting#heading--common-issues ,
# "My pods can't reach the internet or each other (but my MicroK8s host machine can)..."
#
# If you need your microk8s cluster to access the Internet, localops provides script
# microk8s/ufw-allow-microk8s.sh to help you configure your firewall. However, localops
# *DOES NOT* execute it, as this might be a security issue. Please review and customize
# it as you see fit, given your use cases.
#
# Even after correctly configuring your firewall, you may experience connectivity issues,
# after rebooting. Running "microk8s stop" before shutting down should prevent them from
# happening and, even if they do, "microk8s start" and "microk8s stop" should fix them.

- import_playbook: direnv.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Create directory ~/.kube if it does not exist
    file:
      path: "{{ lookup('env', 'HOME') }}/.kube"
      state: directory

  - name: Copy /var/snap/microk8s/current/credentials/kubelet.config to ~/.kube/microk8s
    copy:
      src: /var/snap/microk8s/current/credentials/kubelet.config
      dest: "{{ lookup('env', 'HOME') }}/.kube/microk8s"
      mode: '0600'

  - name: Create file "~/.envrc" if it does not exist
    file:
      path: "{{ lookup('env', 'HOME') }}/.envrc"
      state: touch

  - name: Add microk8s KUBECONFIG to ~/.envrc
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.envrc"
      line: export KUBECONFIG=$HOME/.kube/microk8s

  - name: Add microk8s CONTEXT to ~/.envrc
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.envrc"
      line: export CONTEXT=microk8s

  - name: Update direnv config
    shell: direnv allow

  - debug:
      msg: >
        MicroK8s was installed. If you need your microk8s cluster to access the Internet,
        run script microk8s/ufw-allow-microk8s.sh as root. Be aware it will make changes
        to your firewall that might pose security risks. Even after correctly configuring
        your firewall, you may experience connectivity issues, after rebooting. Running
        'microk8s stop' before shutting down should prevent them from happening and, even
        if they do, 'microk8s start' and 'microk8s stop' should fix them.
