- import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Get Packer latest version
    shell: curl -Ls -o /dev/null -w %{url_effective} https://github.com/hashicorp/packer/releases/latest | sed -e 's|.*/v\(.*\)|\1|'
    args:
      warn: false
    register: version

  # https://www.packer.io/intro/getting-started/install.html#precompiled-binaries
  #
  # Seems the .zip only contains the executable, but, just to be sure...

  - name: Download Packer
    unarchive:
      src: https://releases.hashicorp.com/packer/{{ version.stdout }}/packer_{{ version.stdout }}_linux_amd64.zip
      dest: /tmp
      remote_src: yes

  - name: Copy Packer binary to ~/bin
    copy:
      src: /tmp/packer
      dest: "{{ lookup('env', 'HOME') }}/bin/packer-{{ version.stdout }}"
      mode: '0744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/packer-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/packer"
      state: link
