- import_playbook: create-user-bin.yaml

- hosts: all
  gather_facts: false
  tasks:

  - name: Get Terraform latest version
    shell: curl -Ls -o /dev/null -w %{url_effective} https://github.com/hashicorp/terraform/releases/latest | sed -e 's|.*/v\(.*\)|\1|'
    args:
      warn: false
    register: version

  # https://learn.hashicorp.com/terraform/getting-started/install.html#installing-terraform
  #
  # "After downloading Terraform, unzip the package. Terraform runs as a single binary named terraform.
  # Any other files in the package can be safely removed and Terraform will still function."
  #
  # Seems the .zip only contains the executable, but, just to be sure...

  - name: Download Terraform
    unarchive:
      src: "https://releases.hashicorp.com/terraform/{{ version.stdout }}/terraform_{{ version.stdout }}_linux_amd64.zip"
      dest: /tmp
      remote_src: yes

  - name: Copy Terraform binary to ~/bin
    copy:
      src: /tmp/terraform
      dest: "{{ lookup('env', 'HOME') }}/bin/terraform-{{ version.stdout }}"
      mode: '0744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/terraform-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/terraform"
      state: link
